// dart format width=80
// GENERATED BY drift_dev, DO NOT MODIFY.
// ignore_for_file: type=lint,unused_import
//
import 'package:drift/drift.dart';

class LogisticsOperators extends Table
    with TableInfo<LogisticsOperators, LogisticsOperatorsData> {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  LogisticsOperators(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> id = GeneratedColumn<String>(
    'id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> name = GeneratedColumn<String>(
    'name',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> createdAt = GeneratedColumn<int>(
    'created_at',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  @override
  List<GeneratedColumn> get $columns => [id, name, createdAt];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'logistics_operators';
  @override
  Set<GeneratedColumn> get $primaryKey => {id};
  @override
  LogisticsOperatorsData map(Map<String, dynamic> data, {String? tablePrefix}) {
    final effectivePrefix = tablePrefix != null ? '$tablePrefix.' : '';
    return LogisticsOperatorsData(
      id: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}id'],
      )!,
      name: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}name'],
      )!,
      createdAt: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}created_at'],
      )!,
    );
  }

  @override
  LogisticsOperators createAlias(String alias) {
    return LogisticsOperators(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const ['PRIMARY KEY(id)'];
  @override
  bool get dontWriteConstraints => true;
}

class LogisticsOperatorsData extends DataClass
    implements Insertable<LogisticsOperatorsData> {
  final String id;
  final String name;
  final int createdAt;
  const LogisticsOperatorsData({
    required this.id,
    required this.name,
    required this.createdAt,
  });
  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    map['id'] = Variable<String>(id);
    map['name'] = Variable<String>(name);
    map['created_at'] = Variable<int>(createdAt);
    return map;
  }

  LogisticsOperatorsCompanion toCompanion(bool nullToAbsent) {
    return LogisticsOperatorsCompanion(
      id: Value(id),
      name: Value(name),
      createdAt: Value(createdAt),
    );
  }

  factory LogisticsOperatorsData.fromJson(
    Map<String, dynamic> json, {
    ValueSerializer? serializer,
  }) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return LogisticsOperatorsData(
      id: serializer.fromJson<String>(json['id']),
      name: serializer.fromJson<String>(json['name']),
      createdAt: serializer.fromJson<int>(json['createdAt']),
    );
  }
  @override
  Map<String, dynamic> toJson({ValueSerializer? serializer}) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return <String, dynamic>{
      'id': serializer.toJson<String>(id),
      'name': serializer.toJson<String>(name),
      'createdAt': serializer.toJson<int>(createdAt),
    };
  }

  LogisticsOperatorsData copyWith({String? id, String? name, int? createdAt}) =>
      LogisticsOperatorsData(
        id: id ?? this.id,
        name: name ?? this.name,
        createdAt: createdAt ?? this.createdAt,
      );
  LogisticsOperatorsData copyWithCompanion(LogisticsOperatorsCompanion data) {
    return LogisticsOperatorsData(
      id: data.id.present ? data.id.value : this.id,
      name: data.name.present ? data.name.value : this.name,
      createdAt: data.createdAt.present ? data.createdAt.value : this.createdAt,
    );
  }

  @override
  String toString() {
    return (StringBuffer('LogisticsOperatorsData(')
          ..write('id: $id, ')
          ..write('name: $name, ')
          ..write('createdAt: $createdAt')
          ..write(')'))
        .toString();
  }

  @override
  int get hashCode => Object.hash(id, name, createdAt);
  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      (other is LogisticsOperatorsData &&
          other.id == this.id &&
          other.name == this.name &&
          other.createdAt == this.createdAt);
}

class LogisticsOperatorsCompanion
    extends UpdateCompanion<LogisticsOperatorsData> {
  final Value<String> id;
  final Value<String> name;
  final Value<int> createdAt;
  final Value<int> rowid;
  const LogisticsOperatorsCompanion({
    this.id = const Value.absent(),
    this.name = const Value.absent(),
    this.createdAt = const Value.absent(),
    this.rowid = const Value.absent(),
  });
  LogisticsOperatorsCompanion.insert({
    required String id,
    required String name,
    required int createdAt,
    this.rowid = const Value.absent(),
  }) : id = Value(id),
       name = Value(name),
       createdAt = Value(createdAt);
  static Insertable<LogisticsOperatorsData> custom({
    Expression<String>? id,
    Expression<String>? name,
    Expression<int>? createdAt,
    Expression<int>? rowid,
  }) {
    return RawValuesInsertable({
      if (id != null) 'id': id,
      if (name != null) 'name': name,
      if (createdAt != null) 'created_at': createdAt,
      if (rowid != null) 'rowid': rowid,
    });
  }

  LogisticsOperatorsCompanion copyWith({
    Value<String>? id,
    Value<String>? name,
    Value<int>? createdAt,
    Value<int>? rowid,
  }) {
    return LogisticsOperatorsCompanion(
      id: id ?? this.id,
      name: name ?? this.name,
      createdAt: createdAt ?? this.createdAt,
      rowid: rowid ?? this.rowid,
    );
  }

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    if (id.present) {
      map['id'] = Variable<String>(id.value);
    }
    if (name.present) {
      map['name'] = Variable<String>(name.value);
    }
    if (createdAt.present) {
      map['created_at'] = Variable<int>(createdAt.value);
    }
    if (rowid.present) {
      map['rowid'] = Variable<int>(rowid.value);
    }
    return map;
  }

  @override
  String toString() {
    return (StringBuffer('LogisticsOperatorsCompanion(')
          ..write('id: $id, ')
          ..write('name: $name, ')
          ..write('createdAt: $createdAt, ')
          ..write('rowid: $rowid')
          ..write(')'))
        .toString();
  }
}

class DeliveryRuns extends Table
    with TableInfo<DeliveryRuns, DeliveryRunsData> {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  DeliveryRuns(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> id = GeneratedColumn<String>(
    'id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> operatorId = GeneratedColumn<String>(
    'operator_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints:
        'NOT NULL REFERENCES logistics_operators(id)ON DELETE RESTRICT',
  );
  late final GeneratedColumn<int> startedAt = GeneratedColumn<int>(
    'started_at',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> finishedAt = GeneratedColumn<int>(
    'finished_at',
    aliasedName,
    true,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  @override
  List<GeneratedColumn> get $columns => [id, operatorId, startedAt, finishedAt];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'delivery_runs';
  @override
  Set<GeneratedColumn> get $primaryKey => {id};
  @override
  DeliveryRunsData map(Map<String, dynamic> data, {String? tablePrefix}) {
    final effectivePrefix = tablePrefix != null ? '$tablePrefix.' : '';
    return DeliveryRunsData(
      id: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}id'],
      )!,
      operatorId: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}operator_id'],
      )!,
      startedAt: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}started_at'],
      )!,
      finishedAt: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}finished_at'],
      ),
    );
  }

  @override
  DeliveryRuns createAlias(String alias) {
    return DeliveryRuns(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const ['PRIMARY KEY(id)'];
  @override
  bool get dontWriteConstraints => true;
}

class DeliveryRunsData extends DataClass
    implements Insertable<DeliveryRunsData> {
  final String id;
  final String operatorId;
  final int startedAt;
  final int? finishedAt;
  const DeliveryRunsData({
    required this.id,
    required this.operatorId,
    required this.startedAt,
    this.finishedAt,
  });
  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    map['id'] = Variable<String>(id);
    map['operator_id'] = Variable<String>(operatorId);
    map['started_at'] = Variable<int>(startedAt);
    if (!nullToAbsent || finishedAt != null) {
      map['finished_at'] = Variable<int>(finishedAt);
    }
    return map;
  }

  DeliveryRunsCompanion toCompanion(bool nullToAbsent) {
    return DeliveryRunsCompanion(
      id: Value(id),
      operatorId: Value(operatorId),
      startedAt: Value(startedAt),
      finishedAt: finishedAt == null && nullToAbsent
          ? const Value.absent()
          : Value(finishedAt),
    );
  }

  factory DeliveryRunsData.fromJson(
    Map<String, dynamic> json, {
    ValueSerializer? serializer,
  }) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return DeliveryRunsData(
      id: serializer.fromJson<String>(json['id']),
      operatorId: serializer.fromJson<String>(json['operatorId']),
      startedAt: serializer.fromJson<int>(json['startedAt']),
      finishedAt: serializer.fromJson<int?>(json['finishedAt']),
    );
  }
  @override
  Map<String, dynamic> toJson({ValueSerializer? serializer}) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return <String, dynamic>{
      'id': serializer.toJson<String>(id),
      'operatorId': serializer.toJson<String>(operatorId),
      'startedAt': serializer.toJson<int>(startedAt),
      'finishedAt': serializer.toJson<int?>(finishedAt),
    };
  }

  DeliveryRunsData copyWith({
    String? id,
    String? operatorId,
    int? startedAt,
    Value<int?> finishedAt = const Value.absent(),
  }) => DeliveryRunsData(
    id: id ?? this.id,
    operatorId: operatorId ?? this.operatorId,
    startedAt: startedAt ?? this.startedAt,
    finishedAt: finishedAt.present ? finishedAt.value : this.finishedAt,
  );
  DeliveryRunsData copyWithCompanion(DeliveryRunsCompanion data) {
    return DeliveryRunsData(
      id: data.id.present ? data.id.value : this.id,
      operatorId: data.operatorId.present
          ? data.operatorId.value
          : this.operatorId,
      startedAt: data.startedAt.present ? data.startedAt.value : this.startedAt,
      finishedAt: data.finishedAt.present
          ? data.finishedAt.value
          : this.finishedAt,
    );
  }

  @override
  String toString() {
    return (StringBuffer('DeliveryRunsData(')
          ..write('id: $id, ')
          ..write('operatorId: $operatorId, ')
          ..write('startedAt: $startedAt, ')
          ..write('finishedAt: $finishedAt')
          ..write(')'))
        .toString();
  }

  @override
  int get hashCode => Object.hash(id, operatorId, startedAt, finishedAt);
  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      (other is DeliveryRunsData &&
          other.id == this.id &&
          other.operatorId == this.operatorId &&
          other.startedAt == this.startedAt &&
          other.finishedAt == this.finishedAt);
}

class DeliveryRunsCompanion extends UpdateCompanion<DeliveryRunsData> {
  final Value<String> id;
  final Value<String> operatorId;
  final Value<int> startedAt;
  final Value<int?> finishedAt;
  final Value<int> rowid;
  const DeliveryRunsCompanion({
    this.id = const Value.absent(),
    this.operatorId = const Value.absent(),
    this.startedAt = const Value.absent(),
    this.finishedAt = const Value.absent(),
    this.rowid = const Value.absent(),
  });
  DeliveryRunsCompanion.insert({
    required String id,
    required String operatorId,
    required int startedAt,
    this.finishedAt = const Value.absent(),
    this.rowid = const Value.absent(),
  }) : id = Value(id),
       operatorId = Value(operatorId),
       startedAt = Value(startedAt);
  static Insertable<DeliveryRunsData> custom({
    Expression<String>? id,
    Expression<String>? operatorId,
    Expression<int>? startedAt,
    Expression<int>? finishedAt,
    Expression<int>? rowid,
  }) {
    return RawValuesInsertable({
      if (id != null) 'id': id,
      if (operatorId != null) 'operator_id': operatorId,
      if (startedAt != null) 'started_at': startedAt,
      if (finishedAt != null) 'finished_at': finishedAt,
      if (rowid != null) 'rowid': rowid,
    });
  }

  DeliveryRunsCompanion copyWith({
    Value<String>? id,
    Value<String>? operatorId,
    Value<int>? startedAt,
    Value<int?>? finishedAt,
    Value<int>? rowid,
  }) {
    return DeliveryRunsCompanion(
      id: id ?? this.id,
      operatorId: operatorId ?? this.operatorId,
      startedAt: startedAt ?? this.startedAt,
      finishedAt: finishedAt ?? this.finishedAt,
      rowid: rowid ?? this.rowid,
    );
  }

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    if (id.present) {
      map['id'] = Variable<String>(id.value);
    }
    if (operatorId.present) {
      map['operator_id'] = Variable<String>(operatorId.value);
    }
    if (startedAt.present) {
      map['started_at'] = Variable<int>(startedAt.value);
    }
    if (finishedAt.present) {
      map['finished_at'] = Variable<int>(finishedAt.value);
    }
    if (rowid.present) {
      map['rowid'] = Variable<int>(rowid.value);
    }
    return map;
  }

  @override
  String toString() {
    return (StringBuffer('DeliveryRunsCompanion(')
          ..write('id: $id, ')
          ..write('operatorId: $operatorId, ')
          ..write('startedAt: $startedAt, ')
          ..write('finishedAt: $finishedAt, ')
          ..write('rowid: $rowid')
          ..write(')'))
        .toString();
  }
}

class SyntheticPackages extends Table
    with TableInfo<SyntheticPackages, SyntheticPackagesData> {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  SyntheticPackages(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> id = GeneratedColumn<String>(
    'id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> deliveryRunId = GeneratedColumn<String>(
    'delivery_run_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints:
        'NOT NULL REFERENCES delivery_runs(id)ON DELETE CASCADE',
  );
  late final GeneratedColumn<String> status = GeneratedColumn<String>(
    'status',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL DEFAULT \'pending\' CHECK (status IN (\'pending\', \'delivered\', \'failed\'))',
    defaultValue: const CustomExpression('\'pending\''),
  );
  late final GeneratedColumn<int> createdAt = GeneratedColumn<int>(
    'created_at',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> updatedAt = GeneratedColumn<int>(
    'updated_at',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> needsSync = GeneratedColumn<int>(
    'needs_sync',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL DEFAULT 1 CHECK (needs_sync IN (0, 1))',
    defaultValue: const CustomExpression('1'),
  );
  @override
  List<GeneratedColumn> get $columns => [
    id,
    deliveryRunId,
    status,
    createdAt,
    updatedAt,
    needsSync,
  ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'synthetic_packages';
  @override
  Set<GeneratedColumn> get $primaryKey => {id};
  @override
  SyntheticPackagesData map(Map<String, dynamic> data, {String? tablePrefix}) {
    final effectivePrefix = tablePrefix != null ? '$tablePrefix.' : '';
    return SyntheticPackagesData(
      id: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}id'],
      )!,
      deliveryRunId: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}delivery_run_id'],
      )!,
      status: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}status'],
      )!,
      createdAt: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}created_at'],
      )!,
      updatedAt: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}updated_at'],
      )!,
      needsSync: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}needs_sync'],
      )!,
    );
  }

  @override
  SyntheticPackages createAlias(String alias) {
    return SyntheticPackages(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const ['PRIMARY KEY(id)'];
  @override
  bool get dontWriteConstraints => true;
}

class SyntheticPackagesData extends DataClass
    implements Insertable<SyntheticPackagesData> {
  final String id;
  final String deliveryRunId;
  final String status;
  final int createdAt;
  final int updatedAt;
  final int needsSync;
  const SyntheticPackagesData({
    required this.id,
    required this.deliveryRunId,
    required this.status,
    required this.createdAt,
    required this.updatedAt,
    required this.needsSync,
  });
  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    map['id'] = Variable<String>(id);
    map['delivery_run_id'] = Variable<String>(deliveryRunId);
    map['status'] = Variable<String>(status);
    map['created_at'] = Variable<int>(createdAt);
    map['updated_at'] = Variable<int>(updatedAt);
    map['needs_sync'] = Variable<int>(needsSync);
    return map;
  }

  SyntheticPackagesCompanion toCompanion(bool nullToAbsent) {
    return SyntheticPackagesCompanion(
      id: Value(id),
      deliveryRunId: Value(deliveryRunId),
      status: Value(status),
      createdAt: Value(createdAt),
      updatedAt: Value(updatedAt),
      needsSync: Value(needsSync),
    );
  }

  factory SyntheticPackagesData.fromJson(
    Map<String, dynamic> json, {
    ValueSerializer? serializer,
  }) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return SyntheticPackagesData(
      id: serializer.fromJson<String>(json['id']),
      deliveryRunId: serializer.fromJson<String>(json['deliveryRunId']),
      status: serializer.fromJson<String>(json['status']),
      createdAt: serializer.fromJson<int>(json['createdAt']),
      updatedAt: serializer.fromJson<int>(json['updatedAt']),
      needsSync: serializer.fromJson<int>(json['needsSync']),
    );
  }
  @override
  Map<String, dynamic> toJson({ValueSerializer? serializer}) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return <String, dynamic>{
      'id': serializer.toJson<String>(id),
      'deliveryRunId': serializer.toJson<String>(deliveryRunId),
      'status': serializer.toJson<String>(status),
      'createdAt': serializer.toJson<int>(createdAt),
      'updatedAt': serializer.toJson<int>(updatedAt),
      'needsSync': serializer.toJson<int>(needsSync),
    };
  }

  SyntheticPackagesData copyWith({
    String? id,
    String? deliveryRunId,
    String? status,
    int? createdAt,
    int? updatedAt,
    int? needsSync,
  }) => SyntheticPackagesData(
    id: id ?? this.id,
    deliveryRunId: deliveryRunId ?? this.deliveryRunId,
    status: status ?? this.status,
    createdAt: createdAt ?? this.createdAt,
    updatedAt: updatedAt ?? this.updatedAt,
    needsSync: needsSync ?? this.needsSync,
  );
  SyntheticPackagesData copyWithCompanion(SyntheticPackagesCompanion data) {
    return SyntheticPackagesData(
      id: data.id.present ? data.id.value : this.id,
      deliveryRunId: data.deliveryRunId.present
          ? data.deliveryRunId.value
          : this.deliveryRunId,
      status: data.status.present ? data.status.value : this.status,
      createdAt: data.createdAt.present ? data.createdAt.value : this.createdAt,
      updatedAt: data.updatedAt.present ? data.updatedAt.value : this.updatedAt,
      needsSync: data.needsSync.present ? data.needsSync.value : this.needsSync,
    );
  }

  @override
  String toString() {
    return (StringBuffer('SyntheticPackagesData(')
          ..write('id: $id, ')
          ..write('deliveryRunId: $deliveryRunId, ')
          ..write('status: $status, ')
          ..write('createdAt: $createdAt, ')
          ..write('updatedAt: $updatedAt, ')
          ..write('needsSync: $needsSync')
          ..write(')'))
        .toString();
  }

  @override
  int get hashCode =>
      Object.hash(id, deliveryRunId, status, createdAt, updatedAt, needsSync);
  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      (other is SyntheticPackagesData &&
          other.id == this.id &&
          other.deliveryRunId == this.deliveryRunId &&
          other.status == this.status &&
          other.createdAt == this.createdAt &&
          other.updatedAt == this.updatedAt &&
          other.needsSync == this.needsSync);
}

class SyntheticPackagesCompanion
    extends UpdateCompanion<SyntheticPackagesData> {
  final Value<String> id;
  final Value<String> deliveryRunId;
  final Value<String> status;
  final Value<int> createdAt;
  final Value<int> updatedAt;
  final Value<int> needsSync;
  final Value<int> rowid;
  const SyntheticPackagesCompanion({
    this.id = const Value.absent(),
    this.deliveryRunId = const Value.absent(),
    this.status = const Value.absent(),
    this.createdAt = const Value.absent(),
    this.updatedAt = const Value.absent(),
    this.needsSync = const Value.absent(),
    this.rowid = const Value.absent(),
  });
  SyntheticPackagesCompanion.insert({
    required String id,
    required String deliveryRunId,
    this.status = const Value.absent(),
    required int createdAt,
    required int updatedAt,
    this.needsSync = const Value.absent(),
    this.rowid = const Value.absent(),
  }) : id = Value(id),
       deliveryRunId = Value(deliveryRunId),
       createdAt = Value(createdAt),
       updatedAt = Value(updatedAt);
  static Insertable<SyntheticPackagesData> custom({
    Expression<String>? id,
    Expression<String>? deliveryRunId,
    Expression<String>? status,
    Expression<int>? createdAt,
    Expression<int>? updatedAt,
    Expression<int>? needsSync,
    Expression<int>? rowid,
  }) {
    return RawValuesInsertable({
      if (id != null) 'id': id,
      if (deliveryRunId != null) 'delivery_run_id': deliveryRunId,
      if (status != null) 'status': status,
      if (createdAt != null) 'created_at': createdAt,
      if (updatedAt != null) 'updated_at': updatedAt,
      if (needsSync != null) 'needs_sync': needsSync,
      if (rowid != null) 'rowid': rowid,
    });
  }

  SyntheticPackagesCompanion copyWith({
    Value<String>? id,
    Value<String>? deliveryRunId,
    Value<String>? status,
    Value<int>? createdAt,
    Value<int>? updatedAt,
    Value<int>? needsSync,
    Value<int>? rowid,
  }) {
    return SyntheticPackagesCompanion(
      id: id ?? this.id,
      deliveryRunId: deliveryRunId ?? this.deliveryRunId,
      status: status ?? this.status,
      createdAt: createdAt ?? this.createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
      needsSync: needsSync ?? this.needsSync,
      rowid: rowid ?? this.rowid,
    );
  }

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    if (id.present) {
      map['id'] = Variable<String>(id.value);
    }
    if (deliveryRunId.present) {
      map['delivery_run_id'] = Variable<String>(deliveryRunId.value);
    }
    if (status.present) {
      map['status'] = Variable<String>(status.value);
    }
    if (createdAt.present) {
      map['created_at'] = Variable<int>(createdAt.value);
    }
    if (updatedAt.present) {
      map['updated_at'] = Variable<int>(updatedAt.value);
    }
    if (needsSync.present) {
      map['needs_sync'] = Variable<int>(needsSync.value);
    }
    if (rowid.present) {
      map['rowid'] = Variable<int>(rowid.value);
    }
    return map;
  }

  @override
  String toString() {
    return (StringBuffer('SyntheticPackagesCompanion(')
          ..write('id: $id, ')
          ..write('deliveryRunId: $deliveryRunId, ')
          ..write('status: $status, ')
          ..write('createdAt: $createdAt, ')
          ..write('updatedAt: $updatedAt, ')
          ..write('needsSync: $needsSync, ')
          ..write('rowid: $rowid')
          ..write(')'))
        .toString();
  }
}

class DeliveryEvents extends Table
    with TableInfo<DeliveryEvents, DeliveryEventsData> {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  DeliveryEvents(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> id = GeneratedColumn<String>(
    'id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> packageId = GeneratedColumn<String>(
    'package_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints:
        'NOT NULL REFERENCES synthetic_packages(id)ON DELETE CASCADE',
  );
  late final GeneratedColumn<String> eventType = GeneratedColumn<String>(
    'event_type',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> occurredAt = GeneratedColumn<int>(
    'occurred_at',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> needsSync = GeneratedColumn<int>(
    'needs_sync',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL DEFAULT 1 CHECK (needs_sync IN (0, 1))',
    defaultValue: const CustomExpression('1'),
  );
  @override
  List<GeneratedColumn> get $columns => [
    id,
    packageId,
    eventType,
    occurredAt,
    needsSync,
  ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'delivery_events';
  @override
  Set<GeneratedColumn> get $primaryKey => {id};
  @override
  DeliveryEventsData map(Map<String, dynamic> data, {String? tablePrefix}) {
    final effectivePrefix = tablePrefix != null ? '$tablePrefix.' : '';
    return DeliveryEventsData(
      id: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}id'],
      )!,
      packageId: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}package_id'],
      )!,
      eventType: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}event_type'],
      )!,
      occurredAt: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}occurred_at'],
      )!,
      needsSync: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}needs_sync'],
      )!,
    );
  }

  @override
  DeliveryEvents createAlias(String alias) {
    return DeliveryEvents(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const ['PRIMARY KEY(id)'];
  @override
  bool get dontWriteConstraints => true;
}

class DeliveryEventsData extends DataClass
    implements Insertable<DeliveryEventsData> {
  final String id;
  final String packageId;
  final String eventType;
  final int occurredAt;
  final int needsSync;
  const DeliveryEventsData({
    required this.id,
    required this.packageId,
    required this.eventType,
    required this.occurredAt,
    required this.needsSync,
  });
  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    map['id'] = Variable<String>(id);
    map['package_id'] = Variable<String>(packageId);
    map['event_type'] = Variable<String>(eventType);
    map['occurred_at'] = Variable<int>(occurredAt);
    map['needs_sync'] = Variable<int>(needsSync);
    return map;
  }

  DeliveryEventsCompanion toCompanion(bool nullToAbsent) {
    return DeliveryEventsCompanion(
      id: Value(id),
      packageId: Value(packageId),
      eventType: Value(eventType),
      occurredAt: Value(occurredAt),
      needsSync: Value(needsSync),
    );
  }

  factory DeliveryEventsData.fromJson(
    Map<String, dynamic> json, {
    ValueSerializer? serializer,
  }) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return DeliveryEventsData(
      id: serializer.fromJson<String>(json['id']),
      packageId: serializer.fromJson<String>(json['packageId']),
      eventType: serializer.fromJson<String>(json['eventType']),
      occurredAt: serializer.fromJson<int>(json['occurredAt']),
      needsSync: serializer.fromJson<int>(json['needsSync']),
    );
  }
  @override
  Map<String, dynamic> toJson({ValueSerializer? serializer}) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return <String, dynamic>{
      'id': serializer.toJson<String>(id),
      'packageId': serializer.toJson<String>(packageId),
      'eventType': serializer.toJson<String>(eventType),
      'occurredAt': serializer.toJson<int>(occurredAt),
      'needsSync': serializer.toJson<int>(needsSync),
    };
  }

  DeliveryEventsData copyWith({
    String? id,
    String? packageId,
    String? eventType,
    int? occurredAt,
    int? needsSync,
  }) => DeliveryEventsData(
    id: id ?? this.id,
    packageId: packageId ?? this.packageId,
    eventType: eventType ?? this.eventType,
    occurredAt: occurredAt ?? this.occurredAt,
    needsSync: needsSync ?? this.needsSync,
  );
  DeliveryEventsData copyWithCompanion(DeliveryEventsCompanion data) {
    return DeliveryEventsData(
      id: data.id.present ? data.id.value : this.id,
      packageId: data.packageId.present ? data.packageId.value : this.packageId,
      eventType: data.eventType.present ? data.eventType.value : this.eventType,
      occurredAt: data.occurredAt.present
          ? data.occurredAt.value
          : this.occurredAt,
      needsSync: data.needsSync.present ? data.needsSync.value : this.needsSync,
    );
  }

  @override
  String toString() {
    return (StringBuffer('DeliveryEventsData(')
          ..write('id: $id, ')
          ..write('packageId: $packageId, ')
          ..write('eventType: $eventType, ')
          ..write('occurredAt: $occurredAt, ')
          ..write('needsSync: $needsSync')
          ..write(')'))
        .toString();
  }

  @override
  int get hashCode =>
      Object.hash(id, packageId, eventType, occurredAt, needsSync);
  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      (other is DeliveryEventsData &&
          other.id == this.id &&
          other.packageId == this.packageId &&
          other.eventType == this.eventType &&
          other.occurredAt == this.occurredAt &&
          other.needsSync == this.needsSync);
}

class DeliveryEventsCompanion extends UpdateCompanion<DeliveryEventsData> {
  final Value<String> id;
  final Value<String> packageId;
  final Value<String> eventType;
  final Value<int> occurredAt;
  final Value<int> needsSync;
  final Value<int> rowid;
  const DeliveryEventsCompanion({
    this.id = const Value.absent(),
    this.packageId = const Value.absent(),
    this.eventType = const Value.absent(),
    this.occurredAt = const Value.absent(),
    this.needsSync = const Value.absent(),
    this.rowid = const Value.absent(),
  });
  DeliveryEventsCompanion.insert({
    required String id,
    required String packageId,
    required String eventType,
    required int occurredAt,
    this.needsSync = const Value.absent(),
    this.rowid = const Value.absent(),
  }) : id = Value(id),
       packageId = Value(packageId),
       eventType = Value(eventType),
       occurredAt = Value(occurredAt);
  static Insertable<DeliveryEventsData> custom({
    Expression<String>? id,
    Expression<String>? packageId,
    Expression<String>? eventType,
    Expression<int>? occurredAt,
    Expression<int>? needsSync,
    Expression<int>? rowid,
  }) {
    return RawValuesInsertable({
      if (id != null) 'id': id,
      if (packageId != null) 'package_id': packageId,
      if (eventType != null) 'event_type': eventType,
      if (occurredAt != null) 'occurred_at': occurredAt,
      if (needsSync != null) 'needs_sync': needsSync,
      if (rowid != null) 'rowid': rowid,
    });
  }

  DeliveryEventsCompanion copyWith({
    Value<String>? id,
    Value<String>? packageId,
    Value<String>? eventType,
    Value<int>? occurredAt,
    Value<int>? needsSync,
    Value<int>? rowid,
  }) {
    return DeliveryEventsCompanion(
      id: id ?? this.id,
      packageId: packageId ?? this.packageId,
      eventType: eventType ?? this.eventType,
      occurredAt: occurredAt ?? this.occurredAt,
      needsSync: needsSync ?? this.needsSync,
      rowid: rowid ?? this.rowid,
    );
  }

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    if (id.present) {
      map['id'] = Variable<String>(id.value);
    }
    if (packageId.present) {
      map['package_id'] = Variable<String>(packageId.value);
    }
    if (eventType.present) {
      map['event_type'] = Variable<String>(eventType.value);
    }
    if (occurredAt.present) {
      map['occurred_at'] = Variable<int>(occurredAt.value);
    }
    if (needsSync.present) {
      map['needs_sync'] = Variable<int>(needsSync.value);
    }
    if (rowid.present) {
      map['rowid'] = Variable<int>(rowid.value);
    }
    return map;
  }

  @override
  String toString() {
    return (StringBuffer('DeliveryEventsCompanion(')
          ..write('id: $id, ')
          ..write('packageId: $packageId, ')
          ..write('eventType: $eventType, ')
          ..write('occurredAt: $occurredAt, ')
          ..write('needsSync: $needsSync, ')
          ..write('rowid: $rowid')
          ..write(')'))
        .toString();
  }
}

class DatabaseAtV1 extends GeneratedDatabase {
  DatabaseAtV1(QueryExecutor e) : super(e);
  late final LogisticsOperators logisticsOperators = LogisticsOperators(this);
  late final DeliveryRuns deliveryRuns = DeliveryRuns(this);
  late final SyntheticPackages syntheticPackages = SyntheticPackages(this);
  late final DeliveryEvents deliveryEvents = DeliveryEvents(this);
  @override
  Iterable<TableInfo<Table, Object?>> get allTables =>
      allSchemaEntities.whereType<TableInfo<Table, Object?>>();
  @override
  List<DatabaseSchemaEntity> get allSchemaEntities => [
    logisticsOperators,
    deliveryRuns,
    syntheticPackages,
    deliveryEvents,
  ];
  @override
  StreamQueryUpdateRules get streamUpdateRules => const StreamQueryUpdateRules([
    WritePropagation(
      on: TableUpdateQuery.onTableName(
        'delivery_runs',
        limitUpdateKind: UpdateKind.delete,
      ),
      result: [TableUpdate('synthetic_packages', kind: UpdateKind.delete)],
    ),
    WritePropagation(
      on: TableUpdateQuery.onTableName(
        'synthetic_packages',
        limitUpdateKind: UpdateKind.delete,
      ),
      result: [TableUpdate('delivery_events', kind: UpdateKind.delete)],
    ),
  ]);
  @override
  int get schemaVersion => 1;
}
