// dart format width=80
// GENERATED BY drift_dev, DO NOT MODIFY.
// ignore_for_file: type=lint,unused_import
//
import 'package:drift/drift.dart';

class LogisticsOperators extends Table
    with TableInfo<LogisticsOperators, LogisticsOperatorsData> {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  LogisticsOperators(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> id = GeneratedColumn<String>(
    'id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> name = GeneratedColumn<String>(
    'name',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> createdAt = GeneratedColumn<int>(
    'created_at',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> isActive = GeneratedColumn<int>(
    'is_active',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL DEFAULT 1 CHECK (is_active IN (0, 1))',
    defaultValue: const CustomExpression('1'),
  );
  @override
  List<GeneratedColumn> get $columns => [id, name, createdAt, isActive];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'logistics_operators';
  @override
  Set<GeneratedColumn> get $primaryKey => {id};
  @override
  LogisticsOperatorsData map(Map<String, dynamic> data, {String? tablePrefix}) {
    final effectivePrefix = tablePrefix != null ? '$tablePrefix.' : '';
    return LogisticsOperatorsData(
      id: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}id'],
      )!,
      name: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}name'],
      )!,
      createdAt: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}created_at'],
      )!,
      isActive: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}is_active'],
      )!,
    );
  }

  @override
  LogisticsOperators createAlias(String alias) {
    return LogisticsOperators(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const ['PRIMARY KEY(id)'];
  @override
  bool get dontWriteConstraints => true;
}

class LogisticsOperatorsData extends DataClass
    implements Insertable<LogisticsOperatorsData> {
  final String id;
  final String name;
  final int createdAt;
  final int isActive;
  const LogisticsOperatorsData({
    required this.id,
    required this.name,
    required this.createdAt,
    required this.isActive,
  });
  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    map['id'] = Variable<String>(id);
    map['name'] = Variable<String>(name);
    map['created_at'] = Variable<int>(createdAt);
    map['is_active'] = Variable<int>(isActive);
    return map;
  }

  LogisticsOperatorsCompanion toCompanion(bool nullToAbsent) {
    return LogisticsOperatorsCompanion(
      id: Value(id),
      name: Value(name),
      createdAt: Value(createdAt),
      isActive: Value(isActive),
    );
  }

  factory LogisticsOperatorsData.fromJson(
    Map<String, dynamic> json, {
    ValueSerializer? serializer,
  }) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return LogisticsOperatorsData(
      id: serializer.fromJson<String>(json['id']),
      name: serializer.fromJson<String>(json['name']),
      createdAt: serializer.fromJson<int>(json['createdAt']),
      isActive: serializer.fromJson<int>(json['isActive']),
    );
  }
  @override
  Map<String, dynamic> toJson({ValueSerializer? serializer}) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return <String, dynamic>{
      'id': serializer.toJson<String>(id),
      'name': serializer.toJson<String>(name),
      'createdAt': serializer.toJson<int>(createdAt),
      'isActive': serializer.toJson<int>(isActive),
    };
  }

  LogisticsOperatorsData copyWith({
    String? id,
    String? name,
    int? createdAt,
    int? isActive,
  }) => LogisticsOperatorsData(
    id: id ?? this.id,
    name: name ?? this.name,
    createdAt: createdAt ?? this.createdAt,
    isActive: isActive ?? this.isActive,
  );
  LogisticsOperatorsData copyWithCompanion(LogisticsOperatorsCompanion data) {
    return LogisticsOperatorsData(
      id: data.id.present ? data.id.value : this.id,
      name: data.name.present ? data.name.value : this.name,
      createdAt: data.createdAt.present ? data.createdAt.value : this.createdAt,
      isActive: data.isActive.present ? data.isActive.value : this.isActive,
    );
  }

  @override
  String toString() {
    return (StringBuffer('LogisticsOperatorsData(')
          ..write('id: $id, ')
          ..write('name: $name, ')
          ..write('createdAt: $createdAt, ')
          ..write('isActive: $isActive')
          ..write(')'))
        .toString();
  }

  @override
  int get hashCode => Object.hash(id, name, createdAt, isActive);
  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      (other is LogisticsOperatorsData &&
          other.id == this.id &&
          other.name == this.name &&
          other.createdAt == this.createdAt &&
          other.isActive == this.isActive);
}

class LogisticsOperatorsCompanion
    extends UpdateCompanion<LogisticsOperatorsData> {
  final Value<String> id;
  final Value<String> name;
  final Value<int> createdAt;
  final Value<int> isActive;
  final Value<int> rowid;
  const LogisticsOperatorsCompanion({
    this.id = const Value.absent(),
    this.name = const Value.absent(),
    this.createdAt = const Value.absent(),
    this.isActive = const Value.absent(),
    this.rowid = const Value.absent(),
  });
  LogisticsOperatorsCompanion.insert({
    required String id,
    required String name,
    required int createdAt,
    this.isActive = const Value.absent(),
    this.rowid = const Value.absent(),
  }) : id = Value(id),
       name = Value(name),
       createdAt = Value(createdAt);
  static Insertable<LogisticsOperatorsData> custom({
    Expression<String>? id,
    Expression<String>? name,
    Expression<int>? createdAt,
    Expression<int>? isActive,
    Expression<int>? rowid,
  }) {
    return RawValuesInsertable({
      if (id != null) 'id': id,
      if (name != null) 'name': name,
      if (createdAt != null) 'created_at': createdAt,
      if (isActive != null) 'is_active': isActive,
      if (rowid != null) 'rowid': rowid,
    });
  }

  LogisticsOperatorsCompanion copyWith({
    Value<String>? id,
    Value<String>? name,
    Value<int>? createdAt,
    Value<int>? isActive,
    Value<int>? rowid,
  }) {
    return LogisticsOperatorsCompanion(
      id: id ?? this.id,
      name: name ?? this.name,
      createdAt: createdAt ?? this.createdAt,
      isActive: isActive ?? this.isActive,
      rowid: rowid ?? this.rowid,
    );
  }

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    if (id.present) {
      map['id'] = Variable<String>(id.value);
    }
    if (name.present) {
      map['name'] = Variable<String>(name.value);
    }
    if (createdAt.present) {
      map['created_at'] = Variable<int>(createdAt.value);
    }
    if (isActive.present) {
      map['is_active'] = Variable<int>(isActive.value);
    }
    if (rowid.present) {
      map['rowid'] = Variable<int>(rowid.value);
    }
    return map;
  }

  @override
  String toString() {
    return (StringBuffer('LogisticsOperatorsCompanion(')
          ..write('id: $id, ')
          ..write('name: $name, ')
          ..write('createdAt: $createdAt, ')
          ..write('isActive: $isActive, ')
          ..write('rowid: $rowid')
          ..write(')'))
        .toString();
  }
}

class OperatorTariffs extends Table
    with TableInfo<OperatorTariffs, OperatorTariffsData> {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  OperatorTariffs(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> id = GeneratedColumn<String>(
    'id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> operatorId = GeneratedColumn<String>(
    'operator_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints:
        'NOT NULL REFERENCES logistics_operators(id)ON DELETE RESTRICT',
  );
  late final GeneratedColumn<int> version = GeneratedColumn<int>(
    'version',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> unitPriceMinor = GeneratedColumn<int>(
    'unit_price_minor',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL CHECK (unit_price_minor >= 0)',
  );
  late final GeneratedColumn<String> currency = GeneratedColumn<String>(
    'currency',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> validFrom = GeneratedColumn<int>(
    'valid_from',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> validUntil = GeneratedColumn<int>(
    'valid_until',
    aliasedName,
    true,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<int> isActive = GeneratedColumn<int>(
    'is_active',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL DEFAULT 1 CHECK (is_active IN (0, 1))',
    defaultValue: const CustomExpression('1'),
  );
  late final GeneratedColumn<int> createdAt = GeneratedColumn<int>(
    'created_at',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  @override
  List<GeneratedColumn> get $columns => [
    id,
    operatorId,
    version,
    unitPriceMinor,
    currency,
    validFrom,
    validUntil,
    isActive,
    createdAt,
  ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'operator_tariffs';
  @override
  Set<GeneratedColumn> get $primaryKey => {id};
  @override
  List<Set<GeneratedColumn>> get uniqueKeys => [
    {operatorId, version},
  ];
  @override
  OperatorTariffsData map(Map<String, dynamic> data, {String? tablePrefix}) {
    final effectivePrefix = tablePrefix != null ? '$tablePrefix.' : '';
    return OperatorTariffsData(
      id: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}id'],
      )!,
      operatorId: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}operator_id'],
      )!,
      version: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}version'],
      )!,
      unitPriceMinor: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}unit_price_minor'],
      )!,
      currency: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}currency'],
      )!,
      validFrom: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}valid_from'],
      )!,
      validUntil: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}valid_until'],
      ),
      isActive: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}is_active'],
      )!,
      createdAt: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}created_at'],
      )!,
    );
  }

  @override
  OperatorTariffs createAlias(String alias) {
    return OperatorTariffs(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const [
    'PRIMARY KEY(id)',
    'UNIQUE(operator_id, version)',
  ];
  @override
  bool get dontWriteConstraints => true;
}

class OperatorTariffsData extends DataClass
    implements Insertable<OperatorTariffsData> {
  final String id;
  final String operatorId;
  final int version;
  final int unitPriceMinor;
  final String currency;
  final int validFrom;
  final int? validUntil;
  final int isActive;
  final int createdAt;
  const OperatorTariffsData({
    required this.id,
    required this.operatorId,
    required this.version,
    required this.unitPriceMinor,
    required this.currency,
    required this.validFrom,
    this.validUntil,
    required this.isActive,
    required this.createdAt,
  });
  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    map['id'] = Variable<String>(id);
    map['operator_id'] = Variable<String>(operatorId);
    map['version'] = Variable<int>(version);
    map['unit_price_minor'] = Variable<int>(unitPriceMinor);
    map['currency'] = Variable<String>(currency);
    map['valid_from'] = Variable<int>(validFrom);
    if (!nullToAbsent || validUntil != null) {
      map['valid_until'] = Variable<int>(validUntil);
    }
    map['is_active'] = Variable<int>(isActive);
    map['created_at'] = Variable<int>(createdAt);
    return map;
  }

  OperatorTariffsCompanion toCompanion(bool nullToAbsent) {
    return OperatorTariffsCompanion(
      id: Value(id),
      operatorId: Value(operatorId),
      version: Value(version),
      unitPriceMinor: Value(unitPriceMinor),
      currency: Value(currency),
      validFrom: Value(validFrom),
      validUntil: validUntil == null && nullToAbsent
          ? const Value.absent()
          : Value(validUntil),
      isActive: Value(isActive),
      createdAt: Value(createdAt),
    );
  }

  factory OperatorTariffsData.fromJson(
    Map<String, dynamic> json, {
    ValueSerializer? serializer,
  }) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return OperatorTariffsData(
      id: serializer.fromJson<String>(json['id']),
      operatorId: serializer.fromJson<String>(json['operatorId']),
      version: serializer.fromJson<int>(json['version']),
      unitPriceMinor: serializer.fromJson<int>(json['unitPriceMinor']),
      currency: serializer.fromJson<String>(json['currency']),
      validFrom: serializer.fromJson<int>(json['validFrom']),
      validUntil: serializer.fromJson<int?>(json['validUntil']),
      isActive: serializer.fromJson<int>(json['isActive']),
      createdAt: serializer.fromJson<int>(json['createdAt']),
    );
  }
  @override
  Map<String, dynamic> toJson({ValueSerializer? serializer}) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return <String, dynamic>{
      'id': serializer.toJson<String>(id),
      'operatorId': serializer.toJson<String>(operatorId),
      'version': serializer.toJson<int>(version),
      'unitPriceMinor': serializer.toJson<int>(unitPriceMinor),
      'currency': serializer.toJson<String>(currency),
      'validFrom': serializer.toJson<int>(validFrom),
      'validUntil': serializer.toJson<int?>(validUntil),
      'isActive': serializer.toJson<int>(isActive),
      'createdAt': serializer.toJson<int>(createdAt),
    };
  }

  OperatorTariffsData copyWith({
    String? id,
    String? operatorId,
    int? version,
    int? unitPriceMinor,
    String? currency,
    int? validFrom,
    Value<int?> validUntil = const Value.absent(),
    int? isActive,
    int? createdAt,
  }) => OperatorTariffsData(
    id: id ?? this.id,
    operatorId: operatorId ?? this.operatorId,
    version: version ?? this.version,
    unitPriceMinor: unitPriceMinor ?? this.unitPriceMinor,
    currency: currency ?? this.currency,
    validFrom: validFrom ?? this.validFrom,
    validUntil: validUntil.present ? validUntil.value : this.validUntil,
    isActive: isActive ?? this.isActive,
    createdAt: createdAt ?? this.createdAt,
  );
  OperatorTariffsData copyWithCompanion(OperatorTariffsCompanion data) {
    return OperatorTariffsData(
      id: data.id.present ? data.id.value : this.id,
      operatorId: data.operatorId.present
          ? data.operatorId.value
          : this.operatorId,
      version: data.version.present ? data.version.value : this.version,
      unitPriceMinor: data.unitPriceMinor.present
          ? data.unitPriceMinor.value
          : this.unitPriceMinor,
      currency: data.currency.present ? data.currency.value : this.currency,
      validFrom: data.validFrom.present ? data.validFrom.value : this.validFrom,
      validUntil: data.validUntil.present
          ? data.validUntil.value
          : this.validUntil,
      isActive: data.isActive.present ? data.isActive.value : this.isActive,
      createdAt: data.createdAt.present ? data.createdAt.value : this.createdAt,
    );
  }

  @override
  String toString() {
    return (StringBuffer('OperatorTariffsData(')
          ..write('id: $id, ')
          ..write('operatorId: $operatorId, ')
          ..write('version: $version, ')
          ..write('unitPriceMinor: $unitPriceMinor, ')
          ..write('currency: $currency, ')
          ..write('validFrom: $validFrom, ')
          ..write('validUntil: $validUntil, ')
          ..write('isActive: $isActive, ')
          ..write('createdAt: $createdAt')
          ..write(')'))
        .toString();
  }

  @override
  int get hashCode => Object.hash(
    id,
    operatorId,
    version,
    unitPriceMinor,
    currency,
    validFrom,
    validUntil,
    isActive,
    createdAt,
  );
  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      (other is OperatorTariffsData &&
          other.id == this.id &&
          other.operatorId == this.operatorId &&
          other.version == this.version &&
          other.unitPriceMinor == this.unitPriceMinor &&
          other.currency == this.currency &&
          other.validFrom == this.validFrom &&
          other.validUntil == this.validUntil &&
          other.isActive == this.isActive &&
          other.createdAt == this.createdAt);
}

class OperatorTariffsCompanion extends UpdateCompanion<OperatorTariffsData> {
  final Value<String> id;
  final Value<String> operatorId;
  final Value<int> version;
  final Value<int> unitPriceMinor;
  final Value<String> currency;
  final Value<int> validFrom;
  final Value<int?> validUntil;
  final Value<int> isActive;
  final Value<int> createdAt;
  final Value<int> rowid;
  const OperatorTariffsCompanion({
    this.id = const Value.absent(),
    this.operatorId = const Value.absent(),
    this.version = const Value.absent(),
    this.unitPriceMinor = const Value.absent(),
    this.currency = const Value.absent(),
    this.validFrom = const Value.absent(),
    this.validUntil = const Value.absent(),
    this.isActive = const Value.absent(),
    this.createdAt = const Value.absent(),
    this.rowid = const Value.absent(),
  });
  OperatorTariffsCompanion.insert({
    required String id,
    required String operatorId,
    required int version,
    required int unitPriceMinor,
    required String currency,
    required int validFrom,
    this.validUntil = const Value.absent(),
    this.isActive = const Value.absent(),
    required int createdAt,
    this.rowid = const Value.absent(),
  }) : id = Value(id),
       operatorId = Value(operatorId),
       version = Value(version),
       unitPriceMinor = Value(unitPriceMinor),
       currency = Value(currency),
       validFrom = Value(validFrom),
       createdAt = Value(createdAt);
  static Insertable<OperatorTariffsData> custom({
    Expression<String>? id,
    Expression<String>? operatorId,
    Expression<int>? version,
    Expression<int>? unitPriceMinor,
    Expression<String>? currency,
    Expression<int>? validFrom,
    Expression<int>? validUntil,
    Expression<int>? isActive,
    Expression<int>? createdAt,
    Expression<int>? rowid,
  }) {
    return RawValuesInsertable({
      if (id != null) 'id': id,
      if (operatorId != null) 'operator_id': operatorId,
      if (version != null) 'version': version,
      if (unitPriceMinor != null) 'unit_price_minor': unitPriceMinor,
      if (currency != null) 'currency': currency,
      if (validFrom != null) 'valid_from': validFrom,
      if (validUntil != null) 'valid_until': validUntil,
      if (isActive != null) 'is_active': isActive,
      if (createdAt != null) 'created_at': createdAt,
      if (rowid != null) 'rowid': rowid,
    });
  }

  OperatorTariffsCompanion copyWith({
    Value<String>? id,
    Value<String>? operatorId,
    Value<int>? version,
    Value<int>? unitPriceMinor,
    Value<String>? currency,
    Value<int>? validFrom,
    Value<int?>? validUntil,
    Value<int>? isActive,
    Value<int>? createdAt,
    Value<int>? rowid,
  }) {
    return OperatorTariffsCompanion(
      id: id ?? this.id,
      operatorId: operatorId ?? this.operatorId,
      version: version ?? this.version,
      unitPriceMinor: unitPriceMinor ?? this.unitPriceMinor,
      currency: currency ?? this.currency,
      validFrom: validFrom ?? this.validFrom,
      validUntil: validUntil ?? this.validUntil,
      isActive: isActive ?? this.isActive,
      createdAt: createdAt ?? this.createdAt,
      rowid: rowid ?? this.rowid,
    );
  }

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    if (id.present) {
      map['id'] = Variable<String>(id.value);
    }
    if (operatorId.present) {
      map['operator_id'] = Variable<String>(operatorId.value);
    }
    if (version.present) {
      map['version'] = Variable<int>(version.value);
    }
    if (unitPriceMinor.present) {
      map['unit_price_minor'] = Variable<int>(unitPriceMinor.value);
    }
    if (currency.present) {
      map['currency'] = Variable<String>(currency.value);
    }
    if (validFrom.present) {
      map['valid_from'] = Variable<int>(validFrom.value);
    }
    if (validUntil.present) {
      map['valid_until'] = Variable<int>(validUntil.value);
    }
    if (isActive.present) {
      map['is_active'] = Variable<int>(isActive.value);
    }
    if (createdAt.present) {
      map['created_at'] = Variable<int>(createdAt.value);
    }
    if (rowid.present) {
      map['rowid'] = Variable<int>(rowid.value);
    }
    return map;
  }

  @override
  String toString() {
    return (StringBuffer('OperatorTariffsCompanion(')
          ..write('id: $id, ')
          ..write('operatorId: $operatorId, ')
          ..write('version: $version, ')
          ..write('unitPriceMinor: $unitPriceMinor, ')
          ..write('currency: $currency, ')
          ..write('validFrom: $validFrom, ')
          ..write('validUntil: $validUntil, ')
          ..write('isActive: $isActive, ')
          ..write('createdAt: $createdAt, ')
          ..write('rowid: $rowid')
          ..write(')'))
        .toString();
  }
}

class OperatorLabelProfiles extends Table
    with TableInfo<OperatorLabelProfiles, OperatorLabelProfilesData> {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  OperatorLabelProfiles(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> id = GeneratedColumn<String>(
    'id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> operatorId = GeneratedColumn<String>(
    'operator_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints:
        'NOT NULL REFERENCES logistics_operators(id)ON DELETE CASCADE',
  );
  late final GeneratedColumn<String> marker = GeneratedColumn<String>(
    'marker',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> priority = GeneratedColumn<int>(
    'priority',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL DEFAULT 0',
    defaultValue: const CustomExpression('0'),
  );
  late final GeneratedColumn<int> isActive = GeneratedColumn<int>(
    'is_active',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL DEFAULT 1 CHECK (is_active IN (0, 1))',
    defaultValue: const CustomExpression('1'),
  );
  late final GeneratedColumn<int> createdAt = GeneratedColumn<int>(
    'created_at',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  @override
  List<GeneratedColumn> get $columns => [
    id,
    operatorId,
    marker,
    priority,
    isActive,
    createdAt,
  ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'operator_label_profiles';
  @override
  Set<GeneratedColumn> get $primaryKey => {id};
  @override
  OperatorLabelProfilesData map(
    Map<String, dynamic> data, {
    String? tablePrefix,
  }) {
    final effectivePrefix = tablePrefix != null ? '$tablePrefix.' : '';
    return OperatorLabelProfilesData(
      id: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}id'],
      )!,
      operatorId: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}operator_id'],
      )!,
      marker: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}marker'],
      )!,
      priority: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}priority'],
      )!,
      isActive: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}is_active'],
      )!,
      createdAt: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}created_at'],
      )!,
    );
  }

  @override
  OperatorLabelProfiles createAlias(String alias) {
    return OperatorLabelProfiles(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const ['PRIMARY KEY(id)'];
  @override
  bool get dontWriteConstraints => true;
}

class OperatorLabelProfilesData extends DataClass
    implements Insertable<OperatorLabelProfilesData> {
  final String id;
  final String operatorId;
  final String marker;
  final int priority;
  final int isActive;
  final int createdAt;
  const OperatorLabelProfilesData({
    required this.id,
    required this.operatorId,
    required this.marker,
    required this.priority,
    required this.isActive,
    required this.createdAt,
  });
  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    map['id'] = Variable<String>(id);
    map['operator_id'] = Variable<String>(operatorId);
    map['marker'] = Variable<String>(marker);
    map['priority'] = Variable<int>(priority);
    map['is_active'] = Variable<int>(isActive);
    map['created_at'] = Variable<int>(createdAt);
    return map;
  }

  OperatorLabelProfilesCompanion toCompanion(bool nullToAbsent) {
    return OperatorLabelProfilesCompanion(
      id: Value(id),
      operatorId: Value(operatorId),
      marker: Value(marker),
      priority: Value(priority),
      isActive: Value(isActive),
      createdAt: Value(createdAt),
    );
  }

  factory OperatorLabelProfilesData.fromJson(
    Map<String, dynamic> json, {
    ValueSerializer? serializer,
  }) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return OperatorLabelProfilesData(
      id: serializer.fromJson<String>(json['id']),
      operatorId: serializer.fromJson<String>(json['operatorId']),
      marker: serializer.fromJson<String>(json['marker']),
      priority: serializer.fromJson<int>(json['priority']),
      isActive: serializer.fromJson<int>(json['isActive']),
      createdAt: serializer.fromJson<int>(json['createdAt']),
    );
  }
  @override
  Map<String, dynamic> toJson({ValueSerializer? serializer}) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return <String, dynamic>{
      'id': serializer.toJson<String>(id),
      'operatorId': serializer.toJson<String>(operatorId),
      'marker': serializer.toJson<String>(marker),
      'priority': serializer.toJson<int>(priority),
      'isActive': serializer.toJson<int>(isActive),
      'createdAt': serializer.toJson<int>(createdAt),
    };
  }

  OperatorLabelProfilesData copyWith({
    String? id,
    String? operatorId,
    String? marker,
    int? priority,
    int? isActive,
    int? createdAt,
  }) => OperatorLabelProfilesData(
    id: id ?? this.id,
    operatorId: operatorId ?? this.operatorId,
    marker: marker ?? this.marker,
    priority: priority ?? this.priority,
    isActive: isActive ?? this.isActive,
    createdAt: createdAt ?? this.createdAt,
  );
  OperatorLabelProfilesData copyWithCompanion(
    OperatorLabelProfilesCompanion data,
  ) {
    return OperatorLabelProfilesData(
      id: data.id.present ? data.id.value : this.id,
      operatorId: data.operatorId.present
          ? data.operatorId.value
          : this.operatorId,
      marker: data.marker.present ? data.marker.value : this.marker,
      priority: data.priority.present ? data.priority.value : this.priority,
      isActive: data.isActive.present ? data.isActive.value : this.isActive,
      createdAt: data.createdAt.present ? data.createdAt.value : this.createdAt,
    );
  }

  @override
  String toString() {
    return (StringBuffer('OperatorLabelProfilesData(')
          ..write('id: $id, ')
          ..write('operatorId: $operatorId, ')
          ..write('marker: $marker, ')
          ..write('priority: $priority, ')
          ..write('isActive: $isActive, ')
          ..write('createdAt: $createdAt')
          ..write(')'))
        .toString();
  }

  @override
  int get hashCode =>
      Object.hash(id, operatorId, marker, priority, isActive, createdAt);
  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      (other is OperatorLabelProfilesData &&
          other.id == this.id &&
          other.operatorId == this.operatorId &&
          other.marker == this.marker &&
          other.priority == this.priority &&
          other.isActive == this.isActive &&
          other.createdAt == this.createdAt);
}

class OperatorLabelProfilesCompanion
    extends UpdateCompanion<OperatorLabelProfilesData> {
  final Value<String> id;
  final Value<String> operatorId;
  final Value<String> marker;
  final Value<int> priority;
  final Value<int> isActive;
  final Value<int> createdAt;
  final Value<int> rowid;
  const OperatorLabelProfilesCompanion({
    this.id = const Value.absent(),
    this.operatorId = const Value.absent(),
    this.marker = const Value.absent(),
    this.priority = const Value.absent(),
    this.isActive = const Value.absent(),
    this.createdAt = const Value.absent(),
    this.rowid = const Value.absent(),
  });
  OperatorLabelProfilesCompanion.insert({
    required String id,
    required String operatorId,
    required String marker,
    this.priority = const Value.absent(),
    this.isActive = const Value.absent(),
    required int createdAt,
    this.rowid = const Value.absent(),
  }) : id = Value(id),
       operatorId = Value(operatorId),
       marker = Value(marker),
       createdAt = Value(createdAt);
  static Insertable<OperatorLabelProfilesData> custom({
    Expression<String>? id,
    Expression<String>? operatorId,
    Expression<String>? marker,
    Expression<int>? priority,
    Expression<int>? isActive,
    Expression<int>? createdAt,
    Expression<int>? rowid,
  }) {
    return RawValuesInsertable({
      if (id != null) 'id': id,
      if (operatorId != null) 'operator_id': operatorId,
      if (marker != null) 'marker': marker,
      if (priority != null) 'priority': priority,
      if (isActive != null) 'is_active': isActive,
      if (createdAt != null) 'created_at': createdAt,
      if (rowid != null) 'rowid': rowid,
    });
  }

  OperatorLabelProfilesCompanion copyWith({
    Value<String>? id,
    Value<String>? operatorId,
    Value<String>? marker,
    Value<int>? priority,
    Value<int>? isActive,
    Value<int>? createdAt,
    Value<int>? rowid,
  }) {
    return OperatorLabelProfilesCompanion(
      id: id ?? this.id,
      operatorId: operatorId ?? this.operatorId,
      marker: marker ?? this.marker,
      priority: priority ?? this.priority,
      isActive: isActive ?? this.isActive,
      createdAt: createdAt ?? this.createdAt,
      rowid: rowid ?? this.rowid,
    );
  }

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    if (id.present) {
      map['id'] = Variable<String>(id.value);
    }
    if (operatorId.present) {
      map['operator_id'] = Variable<String>(operatorId.value);
    }
    if (marker.present) {
      map['marker'] = Variable<String>(marker.value);
    }
    if (priority.present) {
      map['priority'] = Variable<int>(priority.value);
    }
    if (isActive.present) {
      map['is_active'] = Variable<int>(isActive.value);
    }
    if (createdAt.present) {
      map['created_at'] = Variable<int>(createdAt.value);
    }
    if (rowid.present) {
      map['rowid'] = Variable<int>(rowid.value);
    }
    return map;
  }

  @override
  String toString() {
    return (StringBuffer('OperatorLabelProfilesCompanion(')
          ..write('id: $id, ')
          ..write('operatorId: $operatorId, ')
          ..write('marker: $marker, ')
          ..write('priority: $priority, ')
          ..write('isActive: $isActive, ')
          ..write('createdAt: $createdAt, ')
          ..write('rowid: $rowid')
          ..write(')'))
        .toString();
  }
}

class DeliveryRuns extends Table
    with TableInfo<DeliveryRuns, DeliveryRunsData> {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  DeliveryRuns(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> id = GeneratedColumn<String>(
    'id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> operatorId = GeneratedColumn<String>(
    'operator_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints:
        'NOT NULL REFERENCES logistics_operators(id)ON DELETE RESTRICT',
  );
  late final GeneratedColumn<int> startedAt = GeneratedColumn<int>(
    'started_at',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> finishedAt = GeneratedColumn<int>(
    'finished_at',
    aliasedName,
    true,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  @override
  List<GeneratedColumn> get $columns => [id, operatorId, startedAt, finishedAt];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'delivery_runs';
  @override
  Set<GeneratedColumn> get $primaryKey => {id};
  @override
  DeliveryRunsData map(Map<String, dynamic> data, {String? tablePrefix}) {
    final effectivePrefix = tablePrefix != null ? '$tablePrefix.' : '';
    return DeliveryRunsData(
      id: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}id'],
      )!,
      operatorId: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}operator_id'],
      )!,
      startedAt: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}started_at'],
      )!,
      finishedAt: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}finished_at'],
      ),
    );
  }

  @override
  DeliveryRuns createAlias(String alias) {
    return DeliveryRuns(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const ['PRIMARY KEY(id)'];
  @override
  bool get dontWriteConstraints => true;
}

class DeliveryRunsData extends DataClass
    implements Insertable<DeliveryRunsData> {
  final String id;
  final String operatorId;
  final int startedAt;
  final int? finishedAt;
  const DeliveryRunsData({
    required this.id,
    required this.operatorId,
    required this.startedAt,
    this.finishedAt,
  });
  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    map['id'] = Variable<String>(id);
    map['operator_id'] = Variable<String>(operatorId);
    map['started_at'] = Variable<int>(startedAt);
    if (!nullToAbsent || finishedAt != null) {
      map['finished_at'] = Variable<int>(finishedAt);
    }
    return map;
  }

  DeliveryRunsCompanion toCompanion(bool nullToAbsent) {
    return DeliveryRunsCompanion(
      id: Value(id),
      operatorId: Value(operatorId),
      startedAt: Value(startedAt),
      finishedAt: finishedAt == null && nullToAbsent
          ? const Value.absent()
          : Value(finishedAt),
    );
  }

  factory DeliveryRunsData.fromJson(
    Map<String, dynamic> json, {
    ValueSerializer? serializer,
  }) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return DeliveryRunsData(
      id: serializer.fromJson<String>(json['id']),
      operatorId: serializer.fromJson<String>(json['operatorId']),
      startedAt: serializer.fromJson<int>(json['startedAt']),
      finishedAt: serializer.fromJson<int?>(json['finishedAt']),
    );
  }
  @override
  Map<String, dynamic> toJson({ValueSerializer? serializer}) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return <String, dynamic>{
      'id': serializer.toJson<String>(id),
      'operatorId': serializer.toJson<String>(operatorId),
      'startedAt': serializer.toJson<int>(startedAt),
      'finishedAt': serializer.toJson<int?>(finishedAt),
    };
  }

  DeliveryRunsData copyWith({
    String? id,
    String? operatorId,
    int? startedAt,
    Value<int?> finishedAt = const Value.absent(),
  }) => DeliveryRunsData(
    id: id ?? this.id,
    operatorId: operatorId ?? this.operatorId,
    startedAt: startedAt ?? this.startedAt,
    finishedAt: finishedAt.present ? finishedAt.value : this.finishedAt,
  );
  DeliveryRunsData copyWithCompanion(DeliveryRunsCompanion data) {
    return DeliveryRunsData(
      id: data.id.present ? data.id.value : this.id,
      operatorId: data.operatorId.present
          ? data.operatorId.value
          : this.operatorId,
      startedAt: data.startedAt.present ? data.startedAt.value : this.startedAt,
      finishedAt: data.finishedAt.present
          ? data.finishedAt.value
          : this.finishedAt,
    );
  }

  @override
  String toString() {
    return (StringBuffer('DeliveryRunsData(')
          ..write('id: $id, ')
          ..write('operatorId: $operatorId, ')
          ..write('startedAt: $startedAt, ')
          ..write('finishedAt: $finishedAt')
          ..write(')'))
        .toString();
  }

  @override
  int get hashCode => Object.hash(id, operatorId, startedAt, finishedAt);
  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      (other is DeliveryRunsData &&
          other.id == this.id &&
          other.operatorId == this.operatorId &&
          other.startedAt == this.startedAt &&
          other.finishedAt == this.finishedAt);
}

class DeliveryRunsCompanion extends UpdateCompanion<DeliveryRunsData> {
  final Value<String> id;
  final Value<String> operatorId;
  final Value<int> startedAt;
  final Value<int?> finishedAt;
  final Value<int> rowid;
  const DeliveryRunsCompanion({
    this.id = const Value.absent(),
    this.operatorId = const Value.absent(),
    this.startedAt = const Value.absent(),
    this.finishedAt = const Value.absent(),
    this.rowid = const Value.absent(),
  });
  DeliveryRunsCompanion.insert({
    required String id,
    required String operatorId,
    required int startedAt,
    this.finishedAt = const Value.absent(),
    this.rowid = const Value.absent(),
  }) : id = Value(id),
       operatorId = Value(operatorId),
       startedAt = Value(startedAt);
  static Insertable<DeliveryRunsData> custom({
    Expression<String>? id,
    Expression<String>? operatorId,
    Expression<int>? startedAt,
    Expression<int>? finishedAt,
    Expression<int>? rowid,
  }) {
    return RawValuesInsertable({
      if (id != null) 'id': id,
      if (operatorId != null) 'operator_id': operatorId,
      if (startedAt != null) 'started_at': startedAt,
      if (finishedAt != null) 'finished_at': finishedAt,
      if (rowid != null) 'rowid': rowid,
    });
  }

  DeliveryRunsCompanion copyWith({
    Value<String>? id,
    Value<String>? operatorId,
    Value<int>? startedAt,
    Value<int?>? finishedAt,
    Value<int>? rowid,
  }) {
    return DeliveryRunsCompanion(
      id: id ?? this.id,
      operatorId: operatorId ?? this.operatorId,
      startedAt: startedAt ?? this.startedAt,
      finishedAt: finishedAt ?? this.finishedAt,
      rowid: rowid ?? this.rowid,
    );
  }

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    if (id.present) {
      map['id'] = Variable<String>(id.value);
    }
    if (operatorId.present) {
      map['operator_id'] = Variable<String>(operatorId.value);
    }
    if (startedAt.present) {
      map['started_at'] = Variable<int>(startedAt.value);
    }
    if (finishedAt.present) {
      map['finished_at'] = Variable<int>(finishedAt.value);
    }
    if (rowid.present) {
      map['rowid'] = Variable<int>(rowid.value);
    }
    return map;
  }

  @override
  String toString() {
    return (StringBuffer('DeliveryRunsCompanion(')
          ..write('id: $id, ')
          ..write('operatorId: $operatorId, ')
          ..write('startedAt: $startedAt, ')
          ..write('finishedAt: $finishedAt, ')
          ..write('rowid: $rowid')
          ..write(')'))
        .toString();
  }
}

class SyntheticPackages extends Table
    with TableInfo<SyntheticPackages, SyntheticPackagesData> {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  SyntheticPackages(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> id = GeneratedColumn<String>(
    'id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> deliveryRunId = GeneratedColumn<String>(
    'delivery_run_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints:
        'NOT NULL REFERENCES delivery_runs(id)ON DELETE CASCADE',
  );
  late final GeneratedColumn<String> status = GeneratedColumn<String>(
    'status',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL DEFAULT \'pending\' CHECK (status IN (\'pending\', \'delivered\', \'failed\'))',
    defaultValue: const CustomExpression('\'pending\''),
  );
  late final GeneratedColumn<String> externalReference =
      GeneratedColumn<String>(
        'external_reference',
        aliasedName,
        true,
        type: DriftSqlType.string,
        requiredDuringInsert: false,
        $customConstraints: 'NULL',
      );
  late final GeneratedColumn<String> identifiedOperatorId =
      GeneratedColumn<String>(
        'identified_operator_id',
        aliasedName,
        true,
        type: DriftSqlType.string,
        requiredDuringInsert: false,
        $customConstraints:
            'NULL REFERENCES logistics_operators(id)ON DELETE RESTRICT',
      );
  late final GeneratedColumn<String> identificationStatus =
      GeneratedColumn<String>(
        'identification_status',
        aliasedName,
        false,
        type: DriftSqlType.string,
        requiredDuringInsert: false,
        $customConstraints: 'NOT NULL DEFAULT \'unknown\' CHECK (identification_status IN (\'identified\', \'low_confidence\', \'unknown\', \'manual\'))',
        defaultValue: const CustomExpression('\'unknown\''),
      );
  late final GeneratedColumn<double> identificationConfidence =
      GeneratedColumn<double>(
        'identification_confidence',
        aliasedName,
        true,
        type: DriftSqlType.double,
        requiredDuringInsert: false,
        $customConstraints: 'NULL',
      );
  late final GeneratedColumn<String> tariffId = GeneratedColumn<String>(
    'tariff_id',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints:
        'NULL REFERENCES operator_tariffs(id)ON DELETE RESTRICT',
  );
  late final GeneratedColumn<int> tariffVersionSnapshot = GeneratedColumn<int>(
    'tariff_version_snapshot',
    aliasedName,
    true,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<int> unitPriceMinorSnapshot = GeneratedColumn<int>(
    'unit_price_minor_snapshot',
    aliasedName,
    true,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<String> currencySnapshot = GeneratedColumn<String>(
    'currency_snapshot',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<int> deliveredAt = GeneratedColumn<int>(
    'delivered_at',
    aliasedName,
    true,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<int> createdAt = GeneratedColumn<int>(
    'created_at',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> updatedAt = GeneratedColumn<int>(
    'updated_at',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> needsSync = GeneratedColumn<int>(
    'needs_sync',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL DEFAULT 1 CHECK (needs_sync IN (0, 1))',
    defaultValue: const CustomExpression('1'),
  );
  @override
  List<GeneratedColumn> get $columns => [
    id,
    deliveryRunId,
    status,
    externalReference,
    identifiedOperatorId,
    identificationStatus,
    identificationConfidence,
    tariffId,
    tariffVersionSnapshot,
    unitPriceMinorSnapshot,
    currencySnapshot,
    deliveredAt,
    createdAt,
    updatedAt,
    needsSync,
  ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'synthetic_packages';
  @override
  Set<GeneratedColumn> get $primaryKey => {id};
  @override
  SyntheticPackagesData map(Map<String, dynamic> data, {String? tablePrefix}) {
    final effectivePrefix = tablePrefix != null ? '$tablePrefix.' : '';
    return SyntheticPackagesData(
      id: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}id'],
      )!,
      deliveryRunId: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}delivery_run_id'],
      )!,
      status: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}status'],
      )!,
      externalReference: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}external_reference'],
      ),
      identifiedOperatorId: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}identified_operator_id'],
      ),
      identificationStatus: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}identification_status'],
      )!,
      identificationConfidence: attachedDatabase.typeMapping.read(
        DriftSqlType.double,
        data['${effectivePrefix}identification_confidence'],
      ),
      tariffId: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}tariff_id'],
      ),
      tariffVersionSnapshot: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}tariff_version_snapshot'],
      ),
      unitPriceMinorSnapshot: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}unit_price_minor_snapshot'],
      ),
      currencySnapshot: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}currency_snapshot'],
      ),
      deliveredAt: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}delivered_at'],
      ),
      createdAt: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}created_at'],
      )!,
      updatedAt: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}updated_at'],
      )!,
      needsSync: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}needs_sync'],
      )!,
    );
  }

  @override
  SyntheticPackages createAlias(String alias) {
    return SyntheticPackages(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const ['PRIMARY KEY(id)'];
  @override
  bool get dontWriteConstraints => true;
}

class SyntheticPackagesData extends DataClass
    implements Insertable<SyntheticPackagesData> {
  final String id;
  final String deliveryRunId;
  final String status;
  final String? externalReference;
  final String? identifiedOperatorId;
  final String identificationStatus;
  final double? identificationConfidence;
  final String? tariffId;
  final int? tariffVersionSnapshot;
  final int? unitPriceMinorSnapshot;
  final String? currencySnapshot;
  final int? deliveredAt;
  final int createdAt;
  final int updatedAt;
  final int needsSync;
  const SyntheticPackagesData({
    required this.id,
    required this.deliveryRunId,
    required this.status,
    this.externalReference,
    this.identifiedOperatorId,
    required this.identificationStatus,
    this.identificationConfidence,
    this.tariffId,
    this.tariffVersionSnapshot,
    this.unitPriceMinorSnapshot,
    this.currencySnapshot,
    this.deliveredAt,
    required this.createdAt,
    required this.updatedAt,
    required this.needsSync,
  });
  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    map['id'] = Variable<String>(id);
    map['delivery_run_id'] = Variable<String>(deliveryRunId);
    map['status'] = Variable<String>(status);
    if (!nullToAbsent || externalReference != null) {
      map['external_reference'] = Variable<String>(externalReference);
    }
    if (!nullToAbsent || identifiedOperatorId != null) {
      map['identified_operator_id'] = Variable<String>(identifiedOperatorId);
    }
    map['identification_status'] = Variable<String>(identificationStatus);
    if (!nullToAbsent || identificationConfidence != null) {
      map['identification_confidence'] = Variable<double>(
        identificationConfidence,
      );
    }
    if (!nullToAbsent || tariffId != null) {
      map['tariff_id'] = Variable<String>(tariffId);
    }
    if (!nullToAbsent || tariffVersionSnapshot != null) {
      map['tariff_version_snapshot'] = Variable<int>(tariffVersionSnapshot);
    }
    if (!nullToAbsent || unitPriceMinorSnapshot != null) {
      map['unit_price_minor_snapshot'] = Variable<int>(unitPriceMinorSnapshot);
    }
    if (!nullToAbsent || currencySnapshot != null) {
      map['currency_snapshot'] = Variable<String>(currencySnapshot);
    }
    if (!nullToAbsent || deliveredAt != null) {
      map['delivered_at'] = Variable<int>(deliveredAt);
    }
    map['created_at'] = Variable<int>(createdAt);
    map['updated_at'] = Variable<int>(updatedAt);
    map['needs_sync'] = Variable<int>(needsSync);
    return map;
  }

  SyntheticPackagesCompanion toCompanion(bool nullToAbsent) {
    return SyntheticPackagesCompanion(
      id: Value(id),
      deliveryRunId: Value(deliveryRunId),
      status: Value(status),
      externalReference: externalReference == null && nullToAbsent
          ? const Value.absent()
          : Value(externalReference),
      identifiedOperatorId: identifiedOperatorId == null && nullToAbsent
          ? const Value.absent()
          : Value(identifiedOperatorId),
      identificationStatus: Value(identificationStatus),
      identificationConfidence: identificationConfidence == null && nullToAbsent
          ? const Value.absent()
          : Value(identificationConfidence),
      tariffId: tariffId == null && nullToAbsent
          ? const Value.absent()
          : Value(tariffId),
      tariffVersionSnapshot: tariffVersionSnapshot == null && nullToAbsent
          ? const Value.absent()
          : Value(tariffVersionSnapshot),
      unitPriceMinorSnapshot: unitPriceMinorSnapshot == null && nullToAbsent
          ? const Value.absent()
          : Value(unitPriceMinorSnapshot),
      currencySnapshot: currencySnapshot == null && nullToAbsent
          ? const Value.absent()
          : Value(currencySnapshot),
      deliveredAt: deliveredAt == null && nullToAbsent
          ? const Value.absent()
          : Value(deliveredAt),
      createdAt: Value(createdAt),
      updatedAt: Value(updatedAt),
      needsSync: Value(needsSync),
    );
  }

  factory SyntheticPackagesData.fromJson(
    Map<String, dynamic> json, {
    ValueSerializer? serializer,
  }) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return SyntheticPackagesData(
      id: serializer.fromJson<String>(json['id']),
      deliveryRunId: serializer.fromJson<String>(json['deliveryRunId']),
      status: serializer.fromJson<String>(json['status']),
      externalReference: serializer.fromJson<String?>(
        json['externalReference'],
      ),
      identifiedOperatorId: serializer.fromJson<String?>(
        json['identifiedOperatorId'],
      ),
      identificationStatus: serializer.fromJson<String>(
        json['identificationStatus'],
      ),
      identificationConfidence: serializer.fromJson<double?>(
        json['identificationConfidence'],
      ),
      tariffId: serializer.fromJson<String?>(json['tariffId']),
      tariffVersionSnapshot: serializer.fromJson<int?>(
        json['tariffVersionSnapshot'],
      ),
      unitPriceMinorSnapshot: serializer.fromJson<int?>(
        json['unitPriceMinorSnapshot'],
      ),
      currencySnapshot: serializer.fromJson<String?>(json['currencySnapshot']),
      deliveredAt: serializer.fromJson<int?>(json['deliveredAt']),
      createdAt: serializer.fromJson<int>(json['createdAt']),
      updatedAt: serializer.fromJson<int>(json['updatedAt']),
      needsSync: serializer.fromJson<int>(json['needsSync']),
    );
  }
  @override
  Map<String, dynamic> toJson({ValueSerializer? serializer}) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return <String, dynamic>{
      'id': serializer.toJson<String>(id),
      'deliveryRunId': serializer.toJson<String>(deliveryRunId),
      'status': serializer.toJson<String>(status),
      'externalReference': serializer.toJson<String?>(externalReference),
      'identifiedOperatorId': serializer.toJson<String?>(identifiedOperatorId),
      'identificationStatus': serializer.toJson<String>(identificationStatus),
      'identificationConfidence': serializer.toJson<double?>(
        identificationConfidence,
      ),
      'tariffId': serializer.toJson<String?>(tariffId),
      'tariffVersionSnapshot': serializer.toJson<int?>(tariffVersionSnapshot),
      'unitPriceMinorSnapshot': serializer.toJson<int?>(unitPriceMinorSnapshot),
      'currencySnapshot': serializer.toJson<String?>(currencySnapshot),
      'deliveredAt': serializer.toJson<int?>(deliveredAt),
      'createdAt': serializer.toJson<int>(createdAt),
      'updatedAt': serializer.toJson<int>(updatedAt),
      'needsSync': serializer.toJson<int>(needsSync),
    };
  }

  SyntheticPackagesData copyWith({
    String? id,
    String? deliveryRunId,
    String? status,
    Value<String?> externalReference = const Value.absent(),
    Value<String?> identifiedOperatorId = const Value.absent(),
    String? identificationStatus,
    Value<double?> identificationConfidence = const Value.absent(),
    Value<String?> tariffId = const Value.absent(),
    Value<int?> tariffVersionSnapshot = const Value.absent(),
    Value<int?> unitPriceMinorSnapshot = const Value.absent(),
    Value<String?> currencySnapshot = const Value.absent(),
    Value<int?> deliveredAt = const Value.absent(),
    int? createdAt,
    int? updatedAt,
    int? needsSync,
  }) => SyntheticPackagesData(
    id: id ?? this.id,
    deliveryRunId: deliveryRunId ?? this.deliveryRunId,
    status: status ?? this.status,
    externalReference: externalReference.present
        ? externalReference.value
        : this.externalReference,
    identifiedOperatorId: identifiedOperatorId.present
        ? identifiedOperatorId.value
        : this.identifiedOperatorId,
    identificationStatus: identificationStatus ?? this.identificationStatus,
    identificationConfidence: identificationConfidence.present
        ? identificationConfidence.value
        : this.identificationConfidence,
    tariffId: tariffId.present ? tariffId.value : this.tariffId,
    tariffVersionSnapshot: tariffVersionSnapshot.present
        ? tariffVersionSnapshot.value
        : this.tariffVersionSnapshot,
    unitPriceMinorSnapshot: unitPriceMinorSnapshot.present
        ? unitPriceMinorSnapshot.value
        : this.unitPriceMinorSnapshot,
    currencySnapshot: currencySnapshot.present
        ? currencySnapshot.value
        : this.currencySnapshot,
    deliveredAt: deliveredAt.present ? deliveredAt.value : this.deliveredAt,
    createdAt: createdAt ?? this.createdAt,
    updatedAt: updatedAt ?? this.updatedAt,
    needsSync: needsSync ?? this.needsSync,
  );
  SyntheticPackagesData copyWithCompanion(SyntheticPackagesCompanion data) {
    return SyntheticPackagesData(
      id: data.id.present ? data.id.value : this.id,
      deliveryRunId: data.deliveryRunId.present
          ? data.deliveryRunId.value
          : this.deliveryRunId,
      status: data.status.present ? data.status.value : this.status,
      externalReference: data.externalReference.present
          ? data.externalReference.value
          : this.externalReference,
      identifiedOperatorId: data.identifiedOperatorId.present
          ? data.identifiedOperatorId.value
          : this.identifiedOperatorId,
      identificationStatus: data.identificationStatus.present
          ? data.identificationStatus.value
          : this.identificationStatus,
      identificationConfidence: data.identificationConfidence.present
          ? data.identificationConfidence.value
          : this.identificationConfidence,
      tariffId: data.tariffId.present ? data.tariffId.value : this.tariffId,
      tariffVersionSnapshot: data.tariffVersionSnapshot.present
          ? data.tariffVersionSnapshot.value
          : this.tariffVersionSnapshot,
      unitPriceMinorSnapshot: data.unitPriceMinorSnapshot.present
          ? data.unitPriceMinorSnapshot.value
          : this.unitPriceMinorSnapshot,
      currencySnapshot: data.currencySnapshot.present
          ? data.currencySnapshot.value
          : this.currencySnapshot,
      deliveredAt: data.deliveredAt.present
          ? data.deliveredAt.value
          : this.deliveredAt,
      createdAt: data.createdAt.present ? data.createdAt.value : this.createdAt,
      updatedAt: data.updatedAt.present ? data.updatedAt.value : this.updatedAt,
      needsSync: data.needsSync.present ? data.needsSync.value : this.needsSync,
    );
  }

  @override
  String toString() {
    return (StringBuffer('SyntheticPackagesData(')
          ..write('id: $id, ')
          ..write('deliveryRunId: $deliveryRunId, ')
          ..write('status: $status, ')
          ..write('externalReference: $externalReference, ')
          ..write('identifiedOperatorId: $identifiedOperatorId, ')
          ..write('identificationStatus: $identificationStatus, ')
          ..write('identificationConfidence: $identificationConfidence, ')
          ..write('tariffId: $tariffId, ')
          ..write('tariffVersionSnapshot: $tariffVersionSnapshot, ')
          ..write('unitPriceMinorSnapshot: $unitPriceMinorSnapshot, ')
          ..write('currencySnapshot: $currencySnapshot, ')
          ..write('deliveredAt: $deliveredAt, ')
          ..write('createdAt: $createdAt, ')
          ..write('updatedAt: $updatedAt, ')
          ..write('needsSync: $needsSync')
          ..write(')'))
        .toString();
  }

  @override
  int get hashCode => Object.hash(
    id,
    deliveryRunId,
    status,
    externalReference,
    identifiedOperatorId,
    identificationStatus,
    identificationConfidence,
    tariffId,
    tariffVersionSnapshot,
    unitPriceMinorSnapshot,
    currencySnapshot,
    deliveredAt,
    createdAt,
    updatedAt,
    needsSync,
  );
  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      (other is SyntheticPackagesData &&
          other.id == this.id &&
          other.deliveryRunId == this.deliveryRunId &&
          other.status == this.status &&
          other.externalReference == this.externalReference &&
          other.identifiedOperatorId == this.identifiedOperatorId &&
          other.identificationStatus == this.identificationStatus &&
          other.identificationConfidence == this.identificationConfidence &&
          other.tariffId == this.tariffId &&
          other.tariffVersionSnapshot == this.tariffVersionSnapshot &&
          other.unitPriceMinorSnapshot == this.unitPriceMinorSnapshot &&
          other.currencySnapshot == this.currencySnapshot &&
          other.deliveredAt == this.deliveredAt &&
          other.createdAt == this.createdAt &&
          other.updatedAt == this.updatedAt &&
          other.needsSync == this.needsSync);
}

class SyntheticPackagesCompanion
    extends UpdateCompanion<SyntheticPackagesData> {
  final Value<String> id;
  final Value<String> deliveryRunId;
  final Value<String> status;
  final Value<String?> externalReference;
  final Value<String?> identifiedOperatorId;
  final Value<String> identificationStatus;
  final Value<double?> identificationConfidence;
  final Value<String?> tariffId;
  final Value<int?> tariffVersionSnapshot;
  final Value<int?> unitPriceMinorSnapshot;
  final Value<String?> currencySnapshot;
  final Value<int?> deliveredAt;
  final Value<int> createdAt;
  final Value<int> updatedAt;
  final Value<int> needsSync;
  final Value<int> rowid;
  const SyntheticPackagesCompanion({
    this.id = const Value.absent(),
    this.deliveryRunId = const Value.absent(),
    this.status = const Value.absent(),
    this.externalReference = const Value.absent(),
    this.identifiedOperatorId = const Value.absent(),
    this.identificationStatus = const Value.absent(),
    this.identificationConfidence = const Value.absent(),
    this.tariffId = const Value.absent(),
    this.tariffVersionSnapshot = const Value.absent(),
    this.unitPriceMinorSnapshot = const Value.absent(),
    this.currencySnapshot = const Value.absent(),
    this.deliveredAt = const Value.absent(),
    this.createdAt = const Value.absent(),
    this.updatedAt = const Value.absent(),
    this.needsSync = const Value.absent(),
    this.rowid = const Value.absent(),
  });
  SyntheticPackagesCompanion.insert({
    required String id,
    required String deliveryRunId,
    this.status = const Value.absent(),
    this.externalReference = const Value.absent(),
    this.identifiedOperatorId = const Value.absent(),
    this.identificationStatus = const Value.absent(),
    this.identificationConfidence = const Value.absent(),
    this.tariffId = const Value.absent(),
    this.tariffVersionSnapshot = const Value.absent(),
    this.unitPriceMinorSnapshot = const Value.absent(),
    this.currencySnapshot = const Value.absent(),
    this.deliveredAt = const Value.absent(),
    required int createdAt,
    required int updatedAt,
    this.needsSync = const Value.absent(),
    this.rowid = const Value.absent(),
  }) : id = Value(id),
       deliveryRunId = Value(deliveryRunId),
       createdAt = Value(createdAt),
       updatedAt = Value(updatedAt);
  static Insertable<SyntheticPackagesData> custom({
    Expression<String>? id,
    Expression<String>? deliveryRunId,
    Expression<String>? status,
    Expression<String>? externalReference,
    Expression<String>? identifiedOperatorId,
    Expression<String>? identificationStatus,
    Expression<double>? identificationConfidence,
    Expression<String>? tariffId,
    Expression<int>? tariffVersionSnapshot,
    Expression<int>? unitPriceMinorSnapshot,
    Expression<String>? currencySnapshot,
    Expression<int>? deliveredAt,
    Expression<int>? createdAt,
    Expression<int>? updatedAt,
    Expression<int>? needsSync,
    Expression<int>? rowid,
  }) {
    return RawValuesInsertable({
      if (id != null) 'id': id,
      if (deliveryRunId != null) 'delivery_run_id': deliveryRunId,
      if (status != null) 'status': status,
      if (externalReference != null) 'external_reference': externalReference,
      if (identifiedOperatorId != null)
        'identified_operator_id': identifiedOperatorId,
      if (identificationStatus != null)
        'identification_status': identificationStatus,
      if (identificationConfidence != null)
        'identification_confidence': identificationConfidence,
      if (tariffId != null) 'tariff_id': tariffId,
      if (tariffVersionSnapshot != null)
        'tariff_version_snapshot': tariffVersionSnapshot,
      if (unitPriceMinorSnapshot != null)
        'unit_price_minor_snapshot': unitPriceMinorSnapshot,
      if (currencySnapshot != null) 'currency_snapshot': currencySnapshot,
      if (deliveredAt != null) 'delivered_at': deliveredAt,
      if (createdAt != null) 'created_at': createdAt,
      if (updatedAt != null) 'updated_at': updatedAt,
      if (needsSync != null) 'needs_sync': needsSync,
      if (rowid != null) 'rowid': rowid,
    });
  }

  SyntheticPackagesCompanion copyWith({
    Value<String>? id,
    Value<String>? deliveryRunId,
    Value<String>? status,
    Value<String?>? externalReference,
    Value<String?>? identifiedOperatorId,
    Value<String>? identificationStatus,
    Value<double?>? identificationConfidence,
    Value<String?>? tariffId,
    Value<int?>? tariffVersionSnapshot,
    Value<int?>? unitPriceMinorSnapshot,
    Value<String?>? currencySnapshot,
    Value<int?>? deliveredAt,
    Value<int>? createdAt,
    Value<int>? updatedAt,
    Value<int>? needsSync,
    Value<int>? rowid,
  }) {
    return SyntheticPackagesCompanion(
      id: id ?? this.id,
      deliveryRunId: deliveryRunId ?? this.deliveryRunId,
      status: status ?? this.status,
      externalReference: externalReference ?? this.externalReference,
      identifiedOperatorId: identifiedOperatorId ?? this.identifiedOperatorId,
      identificationStatus: identificationStatus ?? this.identificationStatus,
      identificationConfidence:
          identificationConfidence ?? this.identificationConfidence,
      tariffId: tariffId ?? this.tariffId,
      tariffVersionSnapshot:
          tariffVersionSnapshot ?? this.tariffVersionSnapshot,
      unitPriceMinorSnapshot:
          unitPriceMinorSnapshot ?? this.unitPriceMinorSnapshot,
      currencySnapshot: currencySnapshot ?? this.currencySnapshot,
      deliveredAt: deliveredAt ?? this.deliveredAt,
      createdAt: createdAt ?? this.createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
      needsSync: needsSync ?? this.needsSync,
      rowid: rowid ?? this.rowid,
    );
  }

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    if (id.present) {
      map['id'] = Variable<String>(id.value);
    }
    if (deliveryRunId.present) {
      map['delivery_run_id'] = Variable<String>(deliveryRunId.value);
    }
    if (status.present) {
      map['status'] = Variable<String>(status.value);
    }
    if (externalReference.present) {
      map['external_reference'] = Variable<String>(externalReference.value);
    }
    if (identifiedOperatorId.present) {
      map['identified_operator_id'] = Variable<String>(
        identifiedOperatorId.value,
      );
    }
    if (identificationStatus.present) {
      map['identification_status'] = Variable<String>(
        identificationStatus.value,
      );
    }
    if (identificationConfidence.present) {
      map['identification_confidence'] = Variable<double>(
        identificationConfidence.value,
      );
    }
    if (tariffId.present) {
      map['tariff_id'] = Variable<String>(tariffId.value);
    }
    if (tariffVersionSnapshot.present) {
      map['tariff_version_snapshot'] = Variable<int>(
        tariffVersionSnapshot.value,
      );
    }
    if (unitPriceMinorSnapshot.present) {
      map['unit_price_minor_snapshot'] = Variable<int>(
        unitPriceMinorSnapshot.value,
      );
    }
    if (currencySnapshot.present) {
      map['currency_snapshot'] = Variable<String>(currencySnapshot.value);
    }
    if (deliveredAt.present) {
      map['delivered_at'] = Variable<int>(deliveredAt.value);
    }
    if (createdAt.present) {
      map['created_at'] = Variable<int>(createdAt.value);
    }
    if (updatedAt.present) {
      map['updated_at'] = Variable<int>(updatedAt.value);
    }
    if (needsSync.present) {
      map['needs_sync'] = Variable<int>(needsSync.value);
    }
    if (rowid.present) {
      map['rowid'] = Variable<int>(rowid.value);
    }
    return map;
  }

  @override
  String toString() {
    return (StringBuffer('SyntheticPackagesCompanion(')
          ..write('id: $id, ')
          ..write('deliveryRunId: $deliveryRunId, ')
          ..write('status: $status, ')
          ..write('externalReference: $externalReference, ')
          ..write('identifiedOperatorId: $identifiedOperatorId, ')
          ..write('identificationStatus: $identificationStatus, ')
          ..write('identificationConfidence: $identificationConfidence, ')
          ..write('tariffId: $tariffId, ')
          ..write('tariffVersionSnapshot: $tariffVersionSnapshot, ')
          ..write('unitPriceMinorSnapshot: $unitPriceMinorSnapshot, ')
          ..write('currencySnapshot: $currencySnapshot, ')
          ..write('deliveredAt: $deliveredAt, ')
          ..write('createdAt: $createdAt, ')
          ..write('updatedAt: $updatedAt, ')
          ..write('needsSync: $needsSync, ')
          ..write('rowid: $rowid')
          ..write(')'))
        .toString();
  }
}

class DeliveryEvents extends Table
    with TableInfo<DeliveryEvents, DeliveryEventsData> {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  DeliveryEvents(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> id = GeneratedColumn<String>(
    'id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> packageId = GeneratedColumn<String>(
    'package_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints:
        'NOT NULL REFERENCES synthetic_packages(id)ON DELETE CASCADE',
  );
  late final GeneratedColumn<String> eventType = GeneratedColumn<String>(
    'event_type',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> occurredAt = GeneratedColumn<int>(
    'occurred_at',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> needsSync = GeneratedColumn<int>(
    'needs_sync',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL DEFAULT 1 CHECK (needs_sync IN (0, 1))',
    defaultValue: const CustomExpression('1'),
  );
  @override
  List<GeneratedColumn> get $columns => [
    id,
    packageId,
    eventType,
    occurredAt,
    needsSync,
  ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'delivery_events';
  @override
  Set<GeneratedColumn> get $primaryKey => {id};
  @override
  DeliveryEventsData map(Map<String, dynamic> data, {String? tablePrefix}) {
    final effectivePrefix = tablePrefix != null ? '$tablePrefix.' : '';
    return DeliveryEventsData(
      id: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}id'],
      )!,
      packageId: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}package_id'],
      )!,
      eventType: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}event_type'],
      )!,
      occurredAt: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}occurred_at'],
      )!,
      needsSync: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}needs_sync'],
      )!,
    );
  }

  @override
  DeliveryEvents createAlias(String alias) {
    return DeliveryEvents(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const ['PRIMARY KEY(id)'];
  @override
  bool get dontWriteConstraints => true;
}

class DeliveryEventsData extends DataClass
    implements Insertable<DeliveryEventsData> {
  final String id;
  final String packageId;
  final String eventType;
  final int occurredAt;
  final int needsSync;
  const DeliveryEventsData({
    required this.id,
    required this.packageId,
    required this.eventType,
    required this.occurredAt,
    required this.needsSync,
  });
  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    map['id'] = Variable<String>(id);
    map['package_id'] = Variable<String>(packageId);
    map['event_type'] = Variable<String>(eventType);
    map['occurred_at'] = Variable<int>(occurredAt);
    map['needs_sync'] = Variable<int>(needsSync);
    return map;
  }

  DeliveryEventsCompanion toCompanion(bool nullToAbsent) {
    return DeliveryEventsCompanion(
      id: Value(id),
      packageId: Value(packageId),
      eventType: Value(eventType),
      occurredAt: Value(occurredAt),
      needsSync: Value(needsSync),
    );
  }

  factory DeliveryEventsData.fromJson(
    Map<String, dynamic> json, {
    ValueSerializer? serializer,
  }) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return DeliveryEventsData(
      id: serializer.fromJson<String>(json['id']),
      packageId: serializer.fromJson<String>(json['packageId']),
      eventType: serializer.fromJson<String>(json['eventType']),
      occurredAt: serializer.fromJson<int>(json['occurredAt']),
      needsSync: serializer.fromJson<int>(json['needsSync']),
    );
  }
  @override
  Map<String, dynamic> toJson({ValueSerializer? serializer}) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return <String, dynamic>{
      'id': serializer.toJson<String>(id),
      'packageId': serializer.toJson<String>(packageId),
      'eventType': serializer.toJson<String>(eventType),
      'occurredAt': serializer.toJson<int>(occurredAt),
      'needsSync': serializer.toJson<int>(needsSync),
    };
  }

  DeliveryEventsData copyWith({
    String? id,
    String? packageId,
    String? eventType,
    int? occurredAt,
    int? needsSync,
  }) => DeliveryEventsData(
    id: id ?? this.id,
    packageId: packageId ?? this.packageId,
    eventType: eventType ?? this.eventType,
    occurredAt: occurredAt ?? this.occurredAt,
    needsSync: needsSync ?? this.needsSync,
  );
  DeliveryEventsData copyWithCompanion(DeliveryEventsCompanion data) {
    return DeliveryEventsData(
      id: data.id.present ? data.id.value : this.id,
      packageId: data.packageId.present ? data.packageId.value : this.packageId,
      eventType: data.eventType.present ? data.eventType.value : this.eventType,
      occurredAt: data.occurredAt.present
          ? data.occurredAt.value
          : this.occurredAt,
      needsSync: data.needsSync.present ? data.needsSync.value : this.needsSync,
    );
  }

  @override
  String toString() {
    return (StringBuffer('DeliveryEventsData(')
          ..write('id: $id, ')
          ..write('packageId: $packageId, ')
          ..write('eventType: $eventType, ')
          ..write('occurredAt: $occurredAt, ')
          ..write('needsSync: $needsSync')
          ..write(')'))
        .toString();
  }

  @override
  int get hashCode =>
      Object.hash(id, packageId, eventType, occurredAt, needsSync);
  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      (other is DeliveryEventsData &&
          other.id == this.id &&
          other.packageId == this.packageId &&
          other.eventType == this.eventType &&
          other.occurredAt == this.occurredAt &&
          other.needsSync == this.needsSync);
}

class DeliveryEventsCompanion extends UpdateCompanion<DeliveryEventsData> {
  final Value<String> id;
  final Value<String> packageId;
  final Value<String> eventType;
  final Value<int> occurredAt;
  final Value<int> needsSync;
  final Value<int> rowid;
  const DeliveryEventsCompanion({
    this.id = const Value.absent(),
    this.packageId = const Value.absent(),
    this.eventType = const Value.absent(),
    this.occurredAt = const Value.absent(),
    this.needsSync = const Value.absent(),
    this.rowid = const Value.absent(),
  });
  DeliveryEventsCompanion.insert({
    required String id,
    required String packageId,
    required String eventType,
    required int occurredAt,
    this.needsSync = const Value.absent(),
    this.rowid = const Value.absent(),
  }) : id = Value(id),
       packageId = Value(packageId),
       eventType = Value(eventType),
       occurredAt = Value(occurredAt);
  static Insertable<DeliveryEventsData> custom({
    Expression<String>? id,
    Expression<String>? packageId,
    Expression<String>? eventType,
    Expression<int>? occurredAt,
    Expression<int>? needsSync,
    Expression<int>? rowid,
  }) {
    return RawValuesInsertable({
      if (id != null) 'id': id,
      if (packageId != null) 'package_id': packageId,
      if (eventType != null) 'event_type': eventType,
      if (occurredAt != null) 'occurred_at': occurredAt,
      if (needsSync != null) 'needs_sync': needsSync,
      if (rowid != null) 'rowid': rowid,
    });
  }

  DeliveryEventsCompanion copyWith({
    Value<String>? id,
    Value<String>? packageId,
    Value<String>? eventType,
    Value<int>? occurredAt,
    Value<int>? needsSync,
    Value<int>? rowid,
  }) {
    return DeliveryEventsCompanion(
      id: id ?? this.id,
      packageId: packageId ?? this.packageId,
      eventType: eventType ?? this.eventType,
      occurredAt: occurredAt ?? this.occurredAt,
      needsSync: needsSync ?? this.needsSync,
      rowid: rowid ?? this.rowid,
    );
  }

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    if (id.present) {
      map['id'] = Variable<String>(id.value);
    }
    if (packageId.present) {
      map['package_id'] = Variable<String>(packageId.value);
    }
    if (eventType.present) {
      map['event_type'] = Variable<String>(eventType.value);
    }
    if (occurredAt.present) {
      map['occurred_at'] = Variable<int>(occurredAt.value);
    }
    if (needsSync.present) {
      map['needs_sync'] = Variable<int>(needsSync.value);
    }
    if (rowid.present) {
      map['rowid'] = Variable<int>(rowid.value);
    }
    return map;
  }

  @override
  String toString() {
    return (StringBuffer('DeliveryEventsCompanion(')
          ..write('id: $id, ')
          ..write('packageId: $packageId, ')
          ..write('eventType: $eventType, ')
          ..write('occurredAt: $occurredAt, ')
          ..write('needsSync: $needsSync, ')
          ..write('rowid: $rowid')
          ..write(')'))
        .toString();
  }
}

class DatabaseAtV3 extends GeneratedDatabase {
  DatabaseAtV3(QueryExecutor e) : super(e);
  late final LogisticsOperators logisticsOperators = LogisticsOperators(this);
  late final OperatorTariffs operatorTariffs = OperatorTariffs(this);
  late final OperatorLabelProfiles operatorLabelProfiles =
      OperatorLabelProfiles(this);
  late final DeliveryRuns deliveryRuns = DeliveryRuns(this);
  late final SyntheticPackages syntheticPackages = SyntheticPackages(this);
  late final DeliveryEvents deliveryEvents = DeliveryEvents(this);
  @override
  Iterable<TableInfo<Table, Object?>> get allTables =>
      allSchemaEntities.whereType<TableInfo<Table, Object?>>();
  @override
  List<DatabaseSchemaEntity> get allSchemaEntities => [
    logisticsOperators,
    operatorTariffs,
    operatorLabelProfiles,
    deliveryRuns,
    syntheticPackages,
    deliveryEvents,
  ];
  @override
  StreamQueryUpdateRules get streamUpdateRules => const StreamQueryUpdateRules([
    WritePropagation(
      on: TableUpdateQuery.onTableName(
        'logistics_operators',
        limitUpdateKind: UpdateKind.delete,
      ),
      result: [TableUpdate('operator_label_profiles', kind: UpdateKind.delete)],
    ),
    WritePropagation(
      on: TableUpdateQuery.onTableName(
        'delivery_runs',
        limitUpdateKind: UpdateKind.delete,
      ),
      result: [TableUpdate('synthetic_packages', kind: UpdateKind.delete)],
    ),
    WritePropagation(
      on: TableUpdateQuery.onTableName(
        'synthetic_packages',
        limitUpdateKind: UpdateKind.delete,
      ),
      result: [TableUpdate('delivery_events', kind: UpdateKind.delete)],
    ),
  ]);
  @override
  int get schemaVersion => 3;
}
